import Foundation
import CoreData

// Extensions to ensure sync properties are available.
// If these cause "invalid redeclaration" errors, it means the properties are already generated by Xcode.
// But if the compiler says "Value of type ... has no member ...", then these are needed.

extension Vehicle {
    @NSManaged public var updatedAt: Date?
    @NSManaged public var deletedAt: Date?
    // createdAt is usually present
}

extension Expense {
    @NSManaged public var updatedAt: Date?
    @NSManaged public var deletedAt: Date?
}

extension ExpenseTemplate {
    @NSManaged public var updatedAt: Date?
    @NSManaged public var deletedAt: Date?
}

extension Sale {
    @NSManaged public var createdAt: Date?
    @NSManaged public var updatedAt: Date?
    @NSManaged public var deletedAt: Date?
}

extension User {
    @NSManaged public var deletedAt: Date?
}

extension FinancialAccount {
    @NSManaged public var updatedAt: Date?
    @NSManaged public var deletedAt: Date?
}

extension Client {
    @NSManaged public var updatedAt: Date?
    @NSManaged public var deletedAt: Date?
}
