-- Insert test listings using existing user ID
INSERT INTO public.listings (
  user_id, title, make, model, year, price, mileage, city, spec, 
  body_type, transmission, fuel_type, condition, accident_history,
  warranty, seller_type, owners_count, tags, description,
  is_draft, status, moderation_status
) VALUES 
(
  '33074802-ba98-4373-a268-071983939e2b'::uuid,
  'BMW 3 Series 2023',
  'bmw',
  '3 Series',
  2023,
  185000,
  15000,
  'Dubai',
  'GCC',
  'sedan',
  'automatic',
  'petrol',
  'excellent',
  'clean',
  'yes',
  'dealer',
  '1',
  ARRAY['featured', 'premium']::text[],
  'Well-maintained BMW 3 Series in excellent condition. Full service history available.',
  false,
  'active',
  'approved'
),
(
  '33074802-ba98-4373-a268-071983939e2b'::uuid,
  'Mercedes GLE 2022',
  'mercedes-benz',
  'GLE',
  2022,
  320000,
  22000,
  'Abu Dhabi',
  'GCC',
  'suv',
  'automatic',
  'petrol',
  'excellent',
  'clean',
  'yes',
  'dealer',
  '1',
  ARRAY['luxury', 'featured']::text[],
  'Luxury Mercedes GLE with premium features and full warranty.',
  false,
  'active',
  'approved'
),
(
  '33074802-ba98-4373-a268-071983939e2b'::uuid,
  'Toyota Camry 2023',
  'toyota',
  'Camry',
  2023,
  95000,
  12000,
  'Sharjah',
  'GCC',
  'sedan',
  'automatic',
  'hybrid',
  'excellent',
  'clean',
  'yes',
  'dealer',
  '1',
  ARRAY['featured', 'eco']::text[],
  'Reliable Toyota Camry Hybrid with excellent fuel economy.',
  false,
  'active',
  'approved'
);